Parameters:
  PublicSubnetId:
    Type: String
  PrivateSubnetId:
    Type: String
  PublicEC2SecurityGroup:
    Type: String
  PrivateEC2SecurityGroup:
    Type: String
  INSTANCETYPE:
    Type: String
    Default: "t2.micro"
  AMI:
    Type: AWS::EC2::Image::Id
    Default: "ami-0866a3c8686eaeeba"
  Environment:
    Type: String
    Default: "Lab1_Nhom14"

Resources:
  PublicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref INSTANCETYPE
      ImageId: !Ref AMI
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref PublicEC2SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${Environment}_PublicEC2Instance"

  PrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref INSTANCETYPE
      ImageId: !Ref AMI
      SubnetId: !Ref PrivateSubnetId
      SecurityGroupIds:
        - !Ref PrivateEC2SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${Environment}_PrivateEC2Instance"

Outputs:
  PublicEC2InstanceId:
    Value: !Ref PublicEC2Instance
  PrivateEC2InstanceId:
    Value: !Ref PrivateEC2Instance
