AWSTemplateFormatVersion: "2010-09-09"
Description: Main Template

Parameters:
  VpcCIDR:
    Type: String
    Default: "192.168.0.0/16"
  PublicSubnetCIDR:
    Type: String
    Default: "192.168.1.0/24"
  PrivateSubnetCIDR:
    Type: String
    Default: "192.168.2.0/24"
  AvailabilityZone:
    Type: String
    Default: "us-east-1a"
  BucketName:
    Type: String
    Default: "nhom14lab02s3bucket"

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${BucketName}.s3.us-east-1.amazonaws.com/nhom14/vpc.yaml"
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        PublicSubnetCIDR: !Ref PublicSubnetCIDR
        PrivateSubnetCIDR: !Ref PrivateSubnetCIDR
        AvailabilityZone: !Ref AvailabilityZone

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${BucketName}.s3.us-east-1.amazonaws.com/nhom14/ec2.yaml"
      Parameters:
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        PublicEC2SecurityGroup: !GetAtt VPCStack.Outputs.PublicSgId
        PrivateEC2SecurityGroup: !GetAtt VPCStack.Outputs.PrivateSgId

Outputs:
  VPCId:
    Value: !GetAtt VPCStack.Outputs.VPCId
  PublicSubnetId:
    Value: !GetAtt VPCStack.Outputs.PublicSubnetId
  PrivateSubnetId:
    Value: !GetAtt VPCStack.Outputs.PrivateSubnetId
  PublicEC2InstanceId:
    Value: !GetAtt EC2Stack.Outputs.PublicEC2InstanceId
  PrivateEC2InstanceId:
    Value: !GetAtt EC2Stack.Outputs.PrivateEC2InstanceId
