AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  KeyName:
    Type: String
    Default: "ec2keypair"
  PublicSubnetId:
    Type: String
    Default: "subnet-022bcf54c34f5941c" # Cập nhật giá trị Public Subnet ID
  PrivateSubnetId:
    Type: String
    Default: "subnet-0d94d1dfda4f3193c" # Cập nhật giá trị Private Subnet ID

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cloudformation-templates-lab1.s3.amazonaws.com/vpc.yaml"
      Parameters:
        PublicSubnetCIDR: "10.0.1.0/24"
        PrivateSubnetCIDR: "10.0.2.0/24"
  
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cloudformation-templates-lab1.s3.amazonaws.com/ec2.yaml"
      Parameters:
        KeyName: !Ref KeyName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetId: !Ref PublicSubnetId
        PrivateSubnetId: !Ref PrivateSubnetId
