AWSTemplateFormatVersion: "2010-09-09"
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cloudformation-templates-lab1.s3.amazonaws.com/vpc.yaml"
  
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://cloudformation-templates-lab1.s3.amazonaws.com/ec2.yaml"
