AWSTemplateFormatVersion: "2010-09-09"
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./cloudformation/vpc.yaml"
  
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./cloudformation/ec2.yaml"
