name: 'Terraform Deploy with Github Actions'

on:
  push:
    branches: [ "lab02/terra" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: "Install Checkov"
      run: pip install checkov

    - name: "Run Checkov"
      run: checkov -f main.tf
      working-directory: Lab02/Terraform/modules/main-modules


    - name: Terraform Init
      run: terraform init
      working-directory: Lab02/Terraform/modules/main-modules

    - name: Terraform Plan
      env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform plan -input=false
      working-directory: Lab02/Terraform/modules/main-modules

    - name: Terraform Apply
      if: (github.ref == 'refs/heads/main' && github.event_name == 'pull_request') 
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve -input=false
      working-directory: Lab02/Terraform/modules/main-modules

    # - name: "Terraform Destroy"
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   run: terraform destroy -auto-approve
    #   working-directory: Lab02/Terraform/modules/main-modules



