name: Hello World

on:
  push:
    branches: [ lab02/terraform ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, World!"

    - name: Run a multi-line script
      run: |
        echo "Hello from"
        echo "GitHub Actions!"
